#include <string.h>
#include "mapperinc.h"

struct unif_board_s {
	const char *name;
	int boardid;
};

#define UNIF_BOARD_START()		static struct unif_board_s boards[] = {
#define UNIF_BOARD_END()		{0,-1}};
#define UNIF_BOARD(s,b)			{s,b},

UNIF_BOARD_START()

	//licensed
	//NROM boards
	UNIF_BOARD("NES-NROM",						B_NROM)
	UNIF_BOARD("NES-NROM-128",					B_NROM)
	UNIF_BOARD("NES-NROM-256",					B_NROM)
	UNIF_BOARD("HVC-NROM-128",					B_NROM)
	UNIF_BOARD("HVC-NROM-256",					B_NROM)
	UNIF_BOARD("IREM-NROM-128",				B_NROM)
	UNIF_BOARD("IREM-NROM-256",				B_NROM)
	UNIF_BOARD("TAITO-NROM-128",				B_NROM)
	UNIF_BOARD("TAITO-NROM-256",				B_NROM)
	UNIF_BOARD("KONAMI-NROM-128",				B_NROM)
	UNIF_BOARD("KONAMI-NROM-256",				B_NROM)
	UNIF_BOARD("JALECO-JF-01",					B_NROM)
	UNIF_BOARD("JALECO-JF-02",					B_NROM)
	UNIF_BOARD("JALECO-JF-03",					B_NROM)
	UNIF_BOARD("JALECO-JF-04",					B_NROM)

	//UxROM boards
	UNIF_BOARD("NES-UNROM",						B_UxROM)
	UNIF_BOARD("HVC-UNROM",						B_UxROM)
	UNIF_BOARD("IREM-UNROM",					B_UxROM)
	UNIF_BOARD("KONAMI-UNROM",					B_UxROM)
	UNIF_BOARD("NES-UOROM",						B_UxROM)
	UNIF_BOARD("HVC-UOROM",						B_UxROM)
	UNIF_BOARD("JALECO-JF-15",					B_UxROM)
	UNIF_BOARD("JALECO-JF-18",					B_UxROM)
	UNIF_BOARD("JALECO-JF-39",					B_UxROM)					//verify this

	//CxROM boards
	UNIF_BOARD("NES-CNROM",						B_CNROM)
	UNIF_BOARD("KONAMI-74*139/74",			B_CNROM)					//appears to be CNROM
	UNIF_BOARD("NES-CPROM",						B_CPROM)

	//DxROM boards
	UNIF_BOARD("NES-DEROM",						B_DxROM)
	UNIF_BOARD("NES-DE1ROM",					B_DxROM)
	UNIF_BOARD("NES-DRROM",						B_DxROM)
	UNIF_BOARD("NAMCOT-3433",					B_DxROM)
	UNIF_BOARD("NAMCOT-3443",					B_DxROM)

	//ExROM boards
	UNIF_BOARD("NES-EKROM",						B_ExROM)
	UNIF_BOARD("NES-ETROM",						B_ExROM)
	UNIF_BOARD("NES-ELROM",						B_ExROM)
	UNIF_BOARD("NES-EWROM",						B_ExROM)

	//SxROM boards
	UNIF_BOARD("NES-SAROM",						B_SxROM)
	UNIF_BOARD("NES-SBROM",						B_SxROM)
	UNIF_BOARD("NES-SCROM",						B_SxROM)
	UNIF_BOARD("NES-SEROM",						B_SxROM)
	UNIF_BOARD("NES-SFROM",						B_SxROM)
	UNIF_BOARD("NES-SGROM",						B_SxROM)
	UNIF_BOARD("NES-SHROM",						B_SxROM)
	UNIF_BOARD("NES-SJROM",						B_SxROM)
	UNIF_BOARD("NES-SKROM",						B_SxROM)
	UNIF_BOARD("NES-SLROM",						B_SxROM)
	UNIF_BOARD("NES-SNROM",						B_SxROM)
	UNIF_BOARD("NES-SOROM",						B_SxROM)
	UNIF_BOARD("NES-SUROM",						B_SxROM)
	UNIF_BOARD("NES-SXROM",						B_SxROM)

	//TxROM boards
	UNIF_BOARD("NES-TLROM",						B_TxROM)
	UNIF_BOARD("NES-TKROM",						B_TxROM)
	UNIF_BOARD("NES-TFROM",						B_TxROM)
	UNIF_BOARD("NES-TBROM",						B_TxROM)
	UNIF_BOARD("NES-TKEPROM",					B_TxROM)

	//FxROM boards
	UNIF_BOARD("NES-FJROM",						B_FxROM)
	UNIF_BOARD("NES-FKROM",						B_FxROM)

	//PxROM boards
	UNIF_BOARD("NES-PNROM",						B_PxROM)
	UNIF_BOARD("NES-PEEOROM",					B_PxROM)
	UNIF_BOARD("HVC-PEEOROM",					B_PxROM)

	//HxROM boards
	UNIF_BOARD("NES-HKROM",						B_HxROM)

	//GxROM/MxROM boards
	UNIF_BOARD("NES-GNROM",						B_GxROM_MxROM)
	UNIF_BOARD("HVC-GNROM",						B_GxROM_MxROM)
	UNIF_BOARD("BANDAI-GNROM",					B_GxROM_MxROM)
	UNIF_BOARD("NES-MHROM",						B_GxROM_MxROM)

	//other boards
	UNIF_BOARD("NES-EVENT",						B_EVENT)

	//jaleco
	UNIF_BOARD("JALECO-JF-23",					B_SS8806)
	UNIF_BOARD("JALECO-JF-24",					B_SS8806)
	UNIF_BOARD("JALECO-JF-25",					B_SS8806)
	UNIF_BOARD("JALECO-JF-27",					B_SS8806)
	UNIF_BOARD("JALECO-JF-29",					B_SS8806)
	UNIF_BOARD("JALECO-JF-30",					B_SS8806)
	UNIF_BOARD("JALECO-JF-31",					B_SS8806)
	UNIF_BOARD("JALECO-JF-32",					B_SS8806)
	UNIF_BOARD("JALECO-JF-33",					B_SS8806)
	UNIF_BOARD("JALECO-JF-34",					B_SS8806)
	UNIF_BOARD("JALECO-JF-35",					B_SS8806)
	UNIF_BOARD("JALECO-JF-36",					B_SS8806)
	UNIF_BOARD("JALECO-JF-37",					B_SS8806)
	UNIF_BOARD("JALECO-JF-38",					B_SS8806)
	UNIF_BOARD("JALECO-JF-40",					B_SS8806)
	UNIF_BOARD("JALECO-JF-41",					B_SS8806)
	UNIF_BOARD("JALECO-JF-05",					B_74x139x74)
	UNIF_BOARD("JALECO-JF-06",					B_74x139x74)
	UNIF_BOARD("JALECO-JF-07",					B_74x139x74)
	UNIF_BOARD("JALECO-JF-08",					B_74x139x74)
	UNIF_BOARD("JALECO-JF-09",					B_74x139x74)
	UNIF_BOARD("JALECO-JF-10",					B_74x139x74)
	UNIF_BOARD("TAITO-74*139/74",				B_74x139x74)

	//bandai
	UNIF_BOARD("BANDAI-KARAOKE",				B_BANDAI_KARAOKE)
	UNIF_BOARD("BANDAI-74*161/161/32",		B_74x161x161x32)

	//taito
	UNIF_BOARD("TAITO-74*161/161/32",		B_74x161x161x32)

	//namcot
	UNIF_BOARD("NAMCOT-163",					B_NAMCOT_163)
	UNIF_BOARD("NAMCOT-175",					B_NAMCOT_163)
	UNIF_BOARD("NAMCOT-340",					B_NAMCOT_163)

	//irem
	UNIF_BOARD("IREM-H3001",					B_IREM_H_3001)

	//unlicensed
	//sachen
	UNIF_BOARD("UNL-SACHEN-8259A",			B_SACHEN_8259A)
	UNIF_BOARD("UNL-SACHEN-8259B",			B_SACHEN_8259B)
	UNIF_BOARD("UNL-SACHEN-8259C",			B_SACHEN_8259C)
	UNIF_BOARD("UNL-SACHEN-8259D",			B_SACHEN_8259D)
	UNIF_BOARD("UNL-SACHEN-74LS374N",		B_SACHEN_74LS374N)
	UNIF_BOARD("UNL-SACHEN-TCA01",			B_SACHEN_TCA01)
	UNIF_BOARD("UNL-SA-NROM",					B_SACHEN_TCA01)
	UNIF_BOARD("UNL-SA-0036",					B_SA_0036)
	UNIF_BOARD("UNL-SA-0037",					B_SA_0037)
	UNIF_BOARD("UNL-SA-72007",					B_SA_72007)
	UNIF_BOARD("UNL-SA-72008",					B_SA_72008)

	//txc corporation
	UNIF_BOARD("UNL-22211",						B_TXC_22211A)
	UNIF_BOARD("UNL-22211-A",					B_TXC_22211A)
	UNIF_BOARD("UNL-22211-B",					B_TXC_22211B)
	UNIF_BOARD("UNL-22211-C",					B_TXC_22211C)
	UNIF_BOARD("TXC-MXMDHTWO",					B_TXC_MXMDHTWO)
	UNIF_BOARD("TXC-TW",							B_TXC_TW)
	UNIF_BOARD("TXC-STRIKEWOLF",				B_TXC_STRIKEWOLF)

	//others
	UNIF_BOARD("UNL-H2288",						B_H2288)
	UNIF_BOARD("BMC-70IN1",						B_70IN1)
	UNIF_BOARD("BMC-70IN1B",					B_70IN1B)
	UNIF_BOARD("MLT-CALTRON6IN1",				B_CALTRON6IN1)
	UNIF_BOARD("BTL-BIOMIRACLEA",				B_BIOMIRACLEA)
	UNIF_BOARD("BTL-MARIO1-MALEE2",			B_MARIO1_MALEE2)

	//74x377
	UNIF_BOARD("COLORDREAMS-74*377",			B_74x377)
	UNIF_BOARD("AGCI-47516",					B_74x377)
	UNIF_BOARD("AVE-NINA-07",					B_74x377)

UNIF_BOARD_END()

int get_unif_boardid(char *str)
{
	int i;

	for(i=0;boards[i].boardid != -1;i++) {
		if(stricmp(str,boards[i].name) == 0)
			return(boards[i].boardid);
	}
	return(B_UNSUPPORTED);
}

const char *get_unif_board(int idx)
{
	if(boards[idx].boardid == -1 || boards[idx].name == 0)
		return(0);
	return(boards[idx].name);
}
